version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform Intersight Pools Module

  A Terraform module to configure Intersight Pools.

  ## Note
  **This module is not meant for direct use.  Use the Example Module below:**

  ## Easy IMM

  [*Easy IMM - Comprehensive Example*](https://github.com/terraform-cisco-modules/easy-imm-comprehensive-example) - A comprehensive example for policies, pools, and profiles.

  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false